version: '2'

volumes:
    db_data:

services:
  gorm-play:
    container_name: gorm-playroom
    image: pocketmedia/gobase
    volumes:
      - ./bin:/opt/service
#    restart: always
#    working_dir: /opt/service
    command: ""
    environment:
      ENV: docker
    links:
      - db
    depends_on:
      - db

  db:
    container_name: gorm-db
    image: mysql:5.7
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gorm-play
      MYSQL_USER: gorm-play
      MYSQL_PASSWORD: 1234