version: '2'

volumes:
    db_data:

services:
  gorm-play:
    container_name: gorm-playroom
    image: pocketmedia/gobase
    volumes:
      - ./bin:/opt/service
    command: ""
    environment:
      ENV: docker
    links:
      - db
    depends_on:
      - start_dependencies

  db:
    container_name: gorm-db
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gorm-play
      MYSQL_USER: gorm-play
      MYSQL_PASSWORD: 1234

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:3306
    environment:
      SLEEP_LENGTH: 0.5
