version: '2'
volumes:
    bin:
services:
  gorm-play:
    container_name: gorm-playroom
    image: "iain17/gobase"
    volumes:
      - "./bin:/opt/service"
    ports:
      - "8080:8080"
    command: ["serve", "--port", "8080", "--host", "0.0.0.0"]
    environment:
      - "ENV=docker"
    links:
      - "mysql"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3308:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=gorm-play"